Repository percona/k8spsmdb-docs, pull requests merged in 2024-05, with the labels that each got.

#121 DOCS-115 Apply new colour scheme, add links and icons to all the projects
  _resource/overrides/partials/header.html
  docs/assets/operators-fav.svg
  docs/assets/operators-mark.svg
  docs/css/design.css
  docs/css/landing.css
  docs/css/operators.css
  docs/css/osano.css
  mkdocs-base.yml
Labels: do-not-merge

#134 experiment on custom options layout
  docs/operator.md
  mkdocs-base.yml
  placeholder-plugin.yaml
  requirements.txt
Labels: enhancement

#133 K8SPSMDB-1016 describe customizing of a cert
  docs/TLS.md
Labels: documentation, pending release

#129 K8SPSMDB-1030 Improve warning about clusterServiceDNSMode=external
  docs/expose.md
  docs/operator.md
Labels: documentation, pending release

#137 K8SPSMDB-865 document arbiter nodeaffinity example
  docs/arbiter.md
Labels: documentation, pending release

#114 K8SPSMDB-1054 don't mark physical-backups as tech preview
  docs/backups.md
Labels: documentation, pending release

#117 K8SPSMDB-999 deprecating service account for backups
  docs/operator.md
Labels: documentation, pending release

#118 K8SPSMDB-1032 add nodePort CR option
  docs/operator.md
Labels: documentation, pending release

#122 K8SPSMDB-1055 add latestRestorableTime
  docs/backups-restore.md
Labels: documentation, pending release

#123 K8SPSMDB-998 add automatic storage scaling
  docs/scaling.md
Labels: documentation, pending release

#124 K8SPSMDB-1071 add securityContext
  docs/operator.md
Labels: documentation, pending release

#126 K8SPSMDB-732 enable TLS for LDAP howto
  docs/ldap.md
Labels: documentation, pending release

#128 K8SPSMDB-940 add service account options
  docs/operator.md
Labels: documentation, pending release

#130 K8SPSMDB-1000 add private Azure endpoint URL
  docs/backups-storage.md
  docs/operator.md
Labels: documentation, pending release

#131 K8SPSMDB-491 add custom issuer options
  docs/operator.md
Labels: documentation, pending release

#132 K8SPSMDB-1004 Allow adding custom port numbers to split horizon URIs
  docs/expose.md
Labels: documentation, pending release

#135 K8SPSMDB-1013 mongo 7 specific changes
  docs/assets/fragments/connectivity.txt
  docs/custom-registry.md
  docs/debug-images.md
  docs/faq.md
  docs/update.md
  docs/update_manually.md
  docs/users.md
Labels: documentation, pending release

#140 K8SPSMDB-780 new unsafe and TLS opts
  docs/TLS.md
  docs/operator.md
Labels: documentation, pending release

#141 K8SPSMDB-951 Add custom backup and restore options
  docs/operator.md
Labels: documentation, pending release

#148 K8SPSMDB-732 add ldapSecret option
  docs/operator.md
Labels: documentation

#146 K8SPSMDB-1026 mention cursor not found error in the expose doc
  docs/expose.md
Labels: documentation

#147 Update compare.md
  docs/compare.md
Labels: documentation
