Repository percona/k8spsmdb-docs, pull requests merged in 2025-03, with the labels that each got.

#94 Update compare.md
  docs/compare.md
Labels: do-not-merge

#227 CLOUD-899 Remove Red Hat Marketplace
  docs/openshift.md
Labels: documentation, do-not-merge

#104 CLOUD-807 add links to docs of the helm charts
  docs/helm.md
Labels: documentation
